# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_over_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=32)),
                ('activity_date', models.DateField()),
                ('field', models.BooleanField(default=False)),
                ('installed', models.CharField(max_length=4096)),
                ('restarted', models.CharField(max_length=4096)),
                ('logs', models.CharField(max_length=1024)),
                ('call_CC', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=2048)),
            ],
        ),
    ]
