# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='over_time',
            name='activity_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='activity_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='activity_date',
            field=models.DateField(db_index=True),
        ),
    ]
