# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_works_passwords_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='passwords_users',
            field=models.CharField(default=b'', max_length=4096),
        ),
    ]
