# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20170123_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='problems',
            field=models.CharField(default=b'', max_length=4096),
        ),
        migrations.AddField(
            model_name='works',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='works',
            name='time_CC',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='works',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
