# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
