# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20170211_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='enddate',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 2, 13, 20, 23, 45, 342192)),
        ),
        migrations.AddField(
            model_name='todo',
            name='startdate',
            field=models.DateField(db_index=True, default=datetime.datetime(2017, 2, 13, 20, 23, 45, 342125)),
        ),
    ]
